## 9章

- 例外処理の構文

```jsx
begin
 # 例外が起きうる処理
rescue
 # 例外が発生した場合の処理
end
```

- 例外自身もオブジェクトとなる
    - 例えばmessageメソッド、backtraceメソッドなどがある
- 情報を取得したい場合の構文

```jsx
begin
 # 例外が起きうる処理
rescue => 例外オブジェクトを格納する変数
 # 例外が発生した場合の処理
end
```

例文

```jsx
begin
  1 / 0
rescue => e
  puts "エラークラス: #{e.class}"
  puts "エラーメッセージ: #{e.message}"
  puts "バックトレース -----"
  puts e.backtrace
  puts "-----"
end
```

省略形としてeやexを使用することが多い

- クラスを指定して補足する例外を限定させることも可能

```jsx
begin
 # 例外が起きうる処理
rescue 補足したい例外クラス
 # 例外が発生した場合の処理
end
```

例文

0で徐算した場合に発生するZeroDivisionError

```jsx
begin
  1 / 0
rescue ZeroDivisionError
  puts "0で除算しました"
end
#=> 0で除算しました
```

ZeroDivisionError以外のエラーが発生した場合はどうなるかと言うと`例外は捕捉されない＝プログラムが以上終了する`

以下は、ZeroDivisionErrorを記載しているコードで存在しないメソッドを呼び出した例

```jsx
begin
  # NoMethodErrorを発生させる
  'abc'.foo
rescue ZeroDivisionError
  puts "0で除算しました"
end
#=> NoMethodError: undefined method `foo' for "abc":String
```

- 例外クラスにも継承関係がある
    - 全ての例外クラスは`Exception`を継承している
- rescue節に指定しない場合はStandardErrorとそのサブクラスが捕捉される。
その場合特殊なエラー(Nomemory ErrorやSystemExit)などは捕捉されない
- 例外処理よりも条件分岐を使うべし
- 例外が発生してもしなくても必ず実行したい処理がある場合はensureに記載

```jsx
begin
 # 例外が発生するかもしれない処理
rescue #(※rescueは任意なので書かなくても問題ない)
 # 例外発生時の処理
ensure
 # 例外の有無に関わらず実行する処理
end
```

- 例外が発生しなかった場合の処理はelseに記載
- 例外処理にも戻り値があり、正常処理の場合はbegin内の最後、例外発生時はrescueの最後が戻り値になる

## 10章

- yieldを使うと渡されたブロックを実行する
ブロックに引数を渡したり、ブロックの戻り値を受け取ったりができる
- yieldとブロックでやり取りする引数は個数の過不足に寛容
